#!/usr/bin/env python3
"""
generate-craft-manifest.py  (v0.1.0)

Generates the CRAFT family machine-readable manifest from canonical source, under
"derive, never duplicate." Zero external dependencies (standard library only).

The CRAFT family spans sibling repositories under the CrossWalkri organization and is
heterogeneous in how its members carry version and metadata. This generator reads each
member's authoritative version from the location the registry names (frontmatter or a
header line), and only cross-checks against the filename version for members whose
filename stem is NOT stable. It surfaces version inconsistencies (for example a
versioned filename that has fallen behind its frontmatter) as findings.

Inputs (read, never written):
  - machine-readable/craft-registry.json : the hand-maintained seed
  - the canonical standard documents in the sibling repos (../../<repo>/<file>)

Output (overwritten):
  - machine-readable/craft-manifest.json : validates against
    standards-family-manifest.schema.json

Run: python3 machine-readable/generate-craft-manifest.py   (from the tools repo root)
Exit codes: 0 clean, 1 findings.
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent          # .../cross-walkri-tools/machine-readable
CODE_ROOT = HERE.parents[1]                      # .../code  (sibling repos live here)
REGISTRY = HERE / "craft-registry.json"
OUT = HERE / "craft-manifest.json"

VERSION_IN_FILENAME = re.compile(r"(\d+)_(\d+)_(\d+)\.md$")
VERSION_IN_HEADER = re.compile(r"v(\d+\.\d+\.\d+)")
FRONTMATTER_VERSION = re.compile(r"^version:\s*(.+)$", re.MULTILINE)

warnings = []


def warn(msg):
    warnings.append(msg)


def frontmatter_version(text):
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    block = text[3:end] if end != -1 else text[3:2000]
    m = FRONTMATTER_VERSION.search(block)
    return m.group(1).strip() if m else None


def header_version(text):
    m = VERSION_IN_HEADER.search(text[:1500])
    return m.group(1) if m else None


def filename_version(name):
    m = VERSION_IN_FILENAME.search(name)
    return ".".join(m.groups()) if m else None


def build_member(entry):
    if entry.get("status") == "planned":
        return {
            "id": entry["id"],
            "name": entry["name"],
            "kind": entry.get("kind", "standard"),
            "version": "unpublished",
            "status": "planned",
            "group": entry.get("role", "planned"),
            "canonicalSource": "https://github.com/CrossWalkri (in preparation)",
            "description": entry.get("description", ""),
        }

    path = CODE_ROOT / entry["repo"] / entry["file"]
    if not path.exists():
        warn(f"NO FILE for {entry['id']}: {path} (is the {entry['repo']} repo cloned as a sibling under {CODE_ROOT}?)")
        return None
    text = path.read_text(encoding="utf-8")

    if entry["versionSource"] == "frontmatter":
        version = frontmatter_version(text)
        src = "frontmatter"
    else:
        version = header_version(text)
        src = "header"
    if not version:
        warn(f"NO VERSION for {entry['id']}: could not read version from {src} of {entry['file']}")
        version = "unknown"

    # Cross-check the filename version only when the stem is not stable.
    if not entry.get("stableStem", False):
        fv = filename_version(entry["file"])
        if fv and fv != version:
            warn(f"VERSION DRIFT for {entry['id']}: filename {fv} lags authoritative {src} version {version} (bump the filename or the {src})")

    member = {
        "id": entry["id"],
        "name": entry["name"],
        "kind": entry.get("kind", "standard"),
        "version": version,
        "status": entry.get("status", "published"),
        "group": entry.get("role", "standard"),
        "canonicalSource": f"{entry['repo']}/{entry['file']}",
        "license": entry.get("license"),
        "description": entry.get("description", ""),
    }
    if "cluster" in entry:
        member["note"] = entry["cluster"]
        warn(f"CLUSTER for {entry['id']}: canonical-document choice undetermined (see note); provisional pointer used")
    return member


def main():
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    fam = reg["family"]
    members = [m for m in (build_member(e) for e in reg["members"]) if m]

    manifest = {
        "$schema": "./standards-family-manifest.schema.json",
        "$comment": "GENERATED by machine-readable/generate-craft-manifest.py from craft-registry.json plus versions read from each member's canonical source. Do not edit by hand; edit the registry or the sources and regenerate.",
        "name": fam["name"],
        "publisher": fam["publisher"],
        "author": fam["author"],
        "version": reg.get("manifestVersion", "0.1.0"),
        "license": fam["license"],
        "description": fam.get("description", ""),
        "homepage": fam.get("homepage"),
        "site": fam.get("site"),
        "canonicalSourceRepo": fam.get("canonicalSourceOrg"),
        "generatedBy": "machine-readable/generate-craft-manifest.py",
        "conformance": {"report": None, "schema": None, "baseline": []},
        "agentInstruction": None,
        "domain": {
            "organization": "CrossWalkri",
            "roles": ["meta", "input", "exit", "reporting", "instrumentation", "primitives"],
            "note": "The family spans sibling repositories; members are heterogeneous in version source (frontmatter or header) and filename-stem stability. See craft-registry.json.",
        },
        "members": members,
    }
    OUT.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    published = [m for m in members if m["status"] == "published"]
    print(f"members: {len(members)} ({len(published)} published, {len(members) - len(published)} planned)")
    print(f"wrote: {OUT.name}")
    if warnings:
        print(f"\n{len(warnings)} finding(s):")
        for w in warnings:
            print(f"  - {w}")
        return 1
    print("\nno findings.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
